Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,8 +16,7 @@ jobs:
         sudo apt update
         sudo apt install -y git bc bison flex libssl-dev make \
         libc6-dev libncurses5-dev clang lld gcc-aarch64-linux-gnu curl \
-        build-essential wget zlib1g-dev libffi-dev libsqlite3-dev \
-        gcc-arm-linux-gnueabi
+        build-essential wget zlib1g-dev libffi-dev libsqlite3-dev zip
 
     # ===== Cache Python2 =====
     - name: Cache Python2
@@ -52,7 +51,6 @@ jobs:
         export CC=clang
         export LD=ld.lld
         export CROSS_COMPILE=aarch64-linux-gnu-
-        export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
         export HOSTCFLAGS="-fcommon"
         export LLVM=1
         export LLVM_IAS=1
@@ -66,11 +64,23 @@ jobs:
         HOSTCFLAGS="-fcommon" \
         KCFLAGS="-w"
 
+    # ===== Pack Artifacts =====
+    - name: Pack Kernel Artifacts
+      if: success()
+      run: |
+        cd out/arch/arm64/boot/
+        if [ -f Image.gz ] && [ -f Image.gz-dtb ]; then
+          zip -r9 Kernel-Redmi9A-KSU.zip Image.gz Image.gz-dtb
+        else
+          echo "Error: Image.gz or Image.gz-dtb not found!"
+          exit 1
+        fi
+
     # ===== Upload =====
-    - name: Upload Kernel Image
+    - name: Upload Kernel Zip
       if: success()
       uses: actions/upload-artifact@v4
       with:
-        name: Image-Redmi9A-KSU
-        path: out/arch/arm64/boot/Image
+        name: Kernel-Redmi9A-KSU-Zip
+        path: out/arch/arm64/boot/Kernel-Redmi9A-KSU.zip
         
